// Generated by CoffeeScript 1.4.0

Ext.Loader.setConfig({
  enabled: true,
  paths: {
    "Phoenix": "app",
    'Ext.ux' : 'resources/ux'
  }
});

Ext.syncRequire(["Ext.Component", "Ext.ComponentManager", "Ext.ComponentQuery"]);
